workflows:
  flutter-ios:
    name: Flutter iOS Build
    max_build_duration: 60
    working_directory: flutter_app
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Install CocoaPods dependencies
        script: cd ios && pod install
      - name: Build iOS
        script: flutter build ios --release --no-codesign
      - name: Create unsigned IPA
        script: |
          cd build/ios/iphoneos
          mkdir -p Payload
          cp -r Runner.app Payload/
          zip -r TheReader.ipa Payload
          rm -rf Payload
    artifacts:
      - build/ios/iphoneos/*.ipa
      - build/ios/iphoneos/Runner.app
    publishing:
      email:
        recipients:
          - chinooknao@gmail.com
        notify:
          success: true
          failure: true

  flutter-android:
    name: Flutter Android Build  
    max_build_duration: 60
    working_directory: flutter_app
    environment:
      flutter: stable
      java: 17
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - chinooknao@gmail.com
        notify:
          success: true
          failure: true
